# Generated by Django 3.0 on 2020-03-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200309_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
