# Generated by Django 3.0 on 2020-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsick', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='is_approved',
            new_name='is_seen',
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
