# Generated by Django 3.0 on 2020-03-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsick', '0004_feedback_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_seen',
        ),
    ]
