# Generated by Django 3.0 on 2020-03-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsick', '0005_remove_report_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
