# Generated by Django 3.0 on 2020-04-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsick', '0006_auto_20200322_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date_posted']},
        ),
    ]
