# Generated by Django 3.0 on 2020-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookleave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='document',
            field=models.FileField(blank=True, default=None, upload_to='documents'),
        ),
    ]
