# Generated by Django 3.0 on 2020-04-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookleave', '0002_leave_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
