# Generated by Django 3.0 on 2020-04-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookleave', '0003_leave_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('sickday', 'Sick Day'), ('vacation', 'Vacation')], max_length=20, verbose_name='Leave Type'),
        ),
    ]
