# Generated by Django 3.0 on 2020-04-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookleave', '0004_auto_20200407_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
